apiVersion: apps/v1
kind: Deployment
metadata:
  name: general-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: general-api
  template:
    metadata:
      labels:
        app: general-api
    spec:
      containers:
      - name: general-api
        image: DOCKER_IMAGE
        ports:
        - containerPort: 8080